# Generated by Django 4.1.3 on 2023-07-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_video_chategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newmodel',
            new_name='chategory',
        ),
    ]
